### ISSUE TITLE
Intel i915_req_ring0 sections overlap

### ISSUE THREAD

**Issue by hfink-daqri** [mikesart/gpuvis#10]
Hi,

I am trying to use gpuvis for analyzing Intel i915 workloads. I am using Debian unstable with a 4.13 kernel (CONFIG_DRM_I915_LOW_LEVEL_TRACEPOINTS is enabled).

I noticed that the i915_req ring0 shows overlapping events. If I'm not mistaken, those should actually be stacked, shouldn't they? I have attached a screenshot, plus the trace data file.

![gpuvis_intel](https://user-images.githubusercontent.com/26539844/31671579-9162eb10-b35a-11e7-8d02-4c5b7ab3972d.png)

[gl_demo_intel_trace.dat.tar.gz](https://github.com/mikesart/gpuvis/files/1391401/gl_demo_intel_trace.dat.tar.gz)

The trace is of a trivial GL demo app (spinning quad).

Do you have any pointers where to start looking on how to fix this?

Thanks,

Heinrich

**Comment by mikesart** [comment]
Hi Heinrich.

Good bug! Should be fixed if you pull the latest. Sorry about that.

If you get a bit busier trace (one that you think would make a good screenshot), would you mind sending it to me? I've only got an intel gpu in an underpowered laptop and I'd like to send something better to the intel folks in response to this:

https://lists.freedesktop.org/archives/intel-gfx/2017-September/137622.html

Would be great if we could get them thinking about an event linking userspace to kernel events.

Thanks so much!

**Comment by hfink-daqri** [comment]
Thanks for the speedy fix :) I'd be very interested in GPUVis working on Intel at the same level as on AMD. I'll see if I can dig out more interesting traces, stay tuned.
