### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [mikesart/gpuvis#14]
I would like to point out that identifiers like “[`_GPUVIS_UTILS_H`](https://github.com/mikesart/gpuvis/blob/20a01d478c14195aa01b9ea2c3dc7aa1ea77946c/src/gpuvis_utils.h#L25 "Update candidate")” and “[`__TDOPEXPR_H__`](https://github.com/mikesart/gpuvis/blob/8644ff4d64c86c7c4e0212f0a3877e6c7acbf29d/src/tdopexpr.h#L24 "Another update candidate")” [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by mikesart** [comment]
Fixed.

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/mikesart/gpuvis/commit/2d1ed4b262d54bfc83abe4245c23e16a03852295 "Renaming of two include guards").

[A few update candidates were left over](https://github.com/mikesart/gpuvis/blob/88811bf36d498e85b2b89e4bd569a0d32135bb0d/src/trace-cmd/list.h#L20 "Update candidate").

**Comment by mikesart** [comment]
list.h is from trace-cmd. Repository here:

https://git.kernel.org/pub/scm/linux/kernel/git/rostedt/trace-cmd.git

Feel free to file a bug against them.

**Comment by elfring** [comment]
Do you care for [any other update candidates a bit more](https://github.com/mikesart/gpuvis/blob/aea43dca88898cc14b2b37853e677a12df9cfc29/src/gpuvis_macros.h#L24 "Update candidate")?
