### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [mikesart/gpuvis#15]
Would you like to add more error handling for return values from functions like the following?
- [malloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [expand_buffer](https://github.com/mikesart/gpuvis/blob/7861baf347dc737dc4dc40e34e7f3ca8b78d135e/src/trace-cmd/trace-seq.c#L67)
- [SDL_CreateMutex](https://wiki.libsdl.org/SDL_CreateMutex "Create a new mutex.") ⇒ [logf_init](https://github.com/mikesart/gpuvis/blob/9f8f9f82ef72e3a56d51be2b12e19012c81b458d/src/gpuvis_utils.cpp#L113)

**Comment by mikesart** [comment]
I added a warnign for SDL_CreateMutex. The malloc in expand_buffer() is from trace-cmd, and should never really be called, and I can't see a clean way to warn on all platforms when it fails, so I'm leaving it. Thanks.

**Comment by elfring** [comment]
[The exception handling is still incomplete](https://github.com/mikesart/gpuvis/commit/d3db865410ff9f3f600e06f74e9e35542b146625#r30316619 "Safe error handling").
