### ISSUE TITLE
Does gpuvis support intel gpu? and how to use gpuvis to trace intel gpu event?

### ISSUE THREAD

**Issue by Jexu** [mikesart/gpuvis#21]
I see there is only one trace file 'amdgpu_trace.zip' for ADM gpu, so does it have similar file for Intel gpu?

**Comment by mikesart** [comment]
Hi Jexu. This is a trace I just captured of the Unreal Shooter Demo on an Intel Skull Canyon NUC.

https://drive.google.com/open?id=1-vADCGhjB_mgKFX1I2rwSxHZG0WW5Lku

Thank you.

**Comment by mikesart** [comment]
Also, the wiki should (hopefully) help with Intel events, and capturing.

https://github.com/mikesart/gpuvis/wiki/trace-cmd
https://github.com/mikesart/gpuvis/wiki/TechDocs-Intel
