### ISSUE TITLE
Scrolling behaviour is weird

### ISSUE THREAD

**Issue by aleixpol** [mikesart/gpuvis#35]
I expected scrolling to pan the view instead of modifying the zoom.
It's especially important since the horizontal scrollbar gets outside the viewport rather easily.

**Comment by mikesart** [comment]
Not sure what you mean by "scrolling"?

**Comment by aleixpol** [comment]
Yes, my bad. Using the wheel on the mouse, two fingers on the touchpad.

**Comment by mikesart** [comment]
Well, right now the design is to click on the graph to move the image, and part of the reason for that is you can move vertically as well. The other reason I believe @Plagman and others wanted this is so you could zoom in and out of an area quickly.

**Comment by aleixpol** [comment]
It could make sense to follow how web browsers do it, zooming with ctrl+wheel.

**Comment by mikesart** [comment]
The current UI is something like some image viewers use which need to pan more than just up/down. For example, shotwell and eog - you click to move around, and mouse wheel zooms. If you have ideas for changing this, feel free to code something up and let some folks give it a try. Thanks.
