### ISSUE TITLE
Ability to load multiple files

### ISSUE THREAD

**Issue by djdeath** [mikesart/gpuvis#38]
This might not be something very interesting for the existing traces, but reading the code I thought it would be possible to load multiple files. Turns out there are few assumptions in the loading code that don't really account for that. Here is a list of a few, nothing major : 
   * event IDs are allocated in trace-read.cpp, unfortunately if I add another "backend" generating events, there will clashes (it was easy to change)
   * the file loader thread seems to be only be able to deal with a single `m_trace_win`

Currently looking at changing the second issue, but I figured it would be good to check so that I don't do something stupid.

My use case is that I have traces generated by the GPU of what is actually running on the HW and I would like to add that to the existing timeline.
This could come handy on Intel HW where we have a microcode able to reorder workloads in the back of the i915 driver.

**Comment by Plagman** [comment]
@lostgoat isn't that similar to what we wanted to do on NVIDIA to merge the hardware-recorded data after the fact?

**Comment by mikesart** [comment]
I don't think the NVIDIA code was ever merged into this branch? Here is the last link I have for that work though:

  https://github.com/adamnv/gpuvis/tree/fecs3

We also talked about how reading multiple files could be useful for showing data from the "perf" tool that you can't get from ftrace. We were going to just merge the data into the stream and not deal with multiple windows though. Or at least display the perf data overlayed.

How were you thinking you wanted to display this information Lionel?

**Comment by djdeath** [comment]
> 
> How were you thinking you wanted to display this information Lionel?

Pretty much like that, an additional row or overlayed on top of the existing i915_request_(in|out) trace points.

**Comment by djdeath** [comment]
Just FYI, I got the timeline from the HW engine going (top row, many more things to add) : 
![Screenshot from 2019-09-27 01-01-50](https://user-images.githubusercontent.com/434333/65728119-9f283380-e0c2-11e9-9aab-0f65fd5c6b68.png)

It requires a recording tool from : https://github.com/djdeath/intel-gpu-tools/tree/wip/i915-perf-tools
You end up with 2 files : 
```
./sample/trace_09-26-2019_01-22-40.dat
./sample/trace_09-26-2019_01-22-40.i915-dat
```

The tool then overlays both types of data.

**Comment by djdeath** [comment]
Closing this as my main use case was merged in master.
