### ISSUE TITLE
i915-perf capturing steps in wiki

### ISSUE THREAD

**Issue by djdeath** [mikesart/gpuvis#42]
Just checking whether that's okay, I would like to add steps to capture traces along with i915-perf data.
I was thinking about adding a section on this page : https://github.com/mikesart/gpuvis/wiki/trace-cmd

But not sure whether it is preferable to have another page?

**Comment by djdeath** [comment]
Steps where put into the the commit message:https://github.com/mikesart/gpuvis/commit/812c8a5f43a0ffe8446494cb53fbbdcc575bc49e

**Comment by mikesart** [comment]
I think that page makes the most sense... feel free to create another page and link to it from there if you want as well though Lionel. Thanks much.
