### ISSUE TITLE
trace-cmd-setup fails on i915/perf_stream_paranoid file not found

### ISSUE THREAD

**Issue by subdiff** [mikesart/gpuvis#47]
On master branch running trace-cmd-setup.sh the following error is reported:
`sysctl: cannot stat /proc/sys/dev/i915/perf_stream_paranoid: No such file or directory`

I tried to set `USE_I915_PERF` to 0 and 1.

Checking out one commit **before** 812c8a5f43a0ffe8446494cb53fbbdcc575bc49e the script works again.

System is kernel 5.6.18-1-MANJARO, AMD GPU and Intel i7, KWinFT Wayland session.

**Comment by mikesart** [comment]
I added a --ignore flag to sysctl in commit 0d234c6. Fixed it on my Debian Testing box, but let me know if that doesn't work for you. Thanks!

**Comment by subdiff** [comment]
Thanks, works! :+1:
