### ISSUE TITLE
No vblank markers on AMD Navi 10

### ISSUE THREAD

**Issue by subdiff** [mikesart/gpuvis#48]
I'm running an AMD RX 5700 (Navi 10) and in the output no vblank markers are shown.

Checkbox `Show crtc0 markers (~16.67ms)` is selected.

On Intel they are shown.

I assume the AMD kernel driver just does not provide these events? Or is there a different issue?

**Comment by mikesart** [comment]
Those should just be drm_vblank_event events, and it looks like those come from drivers/gpu/drm/drm_vblank.c in the kernel. I'd guess they should work on AMD...

Can you do a "trace-cmd report" on your .dat file and see if those "drm_vblank*" events are in there?

**Comment by subdiff** [comment]
Thanks for the info.

I tried to run `trace-cmd report` on the .dat file but got some errors. I was using the trace-cmd AUR package.

So I compiled trace-cmd from master and now I can execute the above command and it shows indeed drm_vblank_event in the output. :+1: 

But now I'm getting an error when trying to open the file in GPUVis:
```
Error handle_otpions: unknown option 11
Error read_trace_file: setjmp error called for trace_06-15-2020_20-11-53.dat.
Error load_trace_file(trace_06-15-2020_20-11-53.dat) failed.
```
Compiling the branch trace-cmd-stable-v2.8 is not possible for me at the moment. Get the error:
```
/usr/bin/ld: /home/roman/dev/ftrace/trace-cmd/src/tracecmd/trace-mem.o:/home/roman/dev/ftrace/trace-cmd/src/tracecmd/trace-mem.c:33: multiple definition of `common_type_field'; /home/roman/dev/ftrace/trace-cmd/src/tracecmd/trace-hist.o:/home/roman/dev/ftrace/trace-cmd/src/tracecmd/trace-hist.c:30: first defined here
```
So it would be nice to make GPUVis work with trace-cmd master. Shall I open a new issue for that?

**Comment by mikesart** [comment]
> Shall I open a new issue for that?

Yes, please. Looks like they added TRACECMD_OPTION_PROCMAPS, TRACECMD_OPTION_TRACEID, and TRACECMD_OPTION_TIME_SHIFT.

Thanks Roman.

**Comment by subdiff** [comment]
Ok, I opened a new issue. I will close this one. I assume the trace-cmd I had from AUR was the culprit. But the trace-cmd situation with AUR is not nice in general. I don't know if that's something you're involved in or if you know somebody to notice about the problem but since GPUVis depends on trace-cmd and many devs probably use Arch based distros it would be nice if this just works (the problem might be Manjaro-only though).
