### ISSUE TITLE
ltime= offset issue

### ISSUE THREAD

**Issue by cnlohr** [mikesart/gpuvis#53]
I really appreciate the ltime change.  It's a huge help.  https://github.com/mikesart/gpuvis/pull/36 

But I'm having issues with it, even in the most basic case.  

```sh
# cat /sys/kernel/tracing/trace_clock
[local] global counter uptime perf mono mono_raw boot
```

And 

```c
uint64_t GetTime()
{
        struct timespec tsp;
        clock_gettime( CLOCK_MONOTONIC, &tsp );
        return (uint64_t)tsp.tv_sec * 1000000LL + tsp.tv_nsec / 1000;
}

int main(int argc, char *argv[])
{
        printf( "test\n");

        int i;
        for( i = 0; ; i++ )
        {
                char st[100];
                sprintf( st, "[XXX] Event %d A", i );
                EventWriteString( st );
                usleep(100);
                sprintf( st, "[XXX] Event %d B", i );
                EventWriteString( st );
                usleep(100);
                sprintf( st, "[XXX] Event %d C", i );
                EventWriteString( st );
                usleep(100);
                sprintf( st, "[XXX] Event %d D ltime=%llu", i, GetTime()*1000 );
                EventWriteString( st );
                usleep(100);
                sprintf( st, "[XXX] Event %d E ltime=%llu", i, GetTime()*1000 );
                EventWriteString( st );
                usleep(100);
                sprintf( st, "[XXX] Event %d F ltime=%llu", i, GetTime() *1000);
                EventWriteString( st );
                usleep(1000);
                sprintf( st, "[XXX] Event %d G", i );
                EventWriteString( st );
                usleep(100);
                sprintf( st, "[XXX] Event %d H ltime=%llu", i, GetTime()*1000 );
                EventWriteString( st );
                sprintf( st, "[XXX] Event %d I", i );
                EventWriteString( st );
                usleep(10000);
        }

        return EXIT_SUCCESS;
}
```

I end up having things hop around on the timeline.  Notice A, B, and C are good, but D, E and F are to late,then it hps back before for G and I.  This is probably not an issue directly with gpuvis, but I was wondering if there was some trick to doing this?  different time base?  Maybe some way of specifying a "now" synchronous event?  To synchronize ltime and system time?

![image](https://user-images.githubusercontent.com/2748168/98462160-ed818000-2166-11eb-8275-399224c0471b.png)

**Comment by Plagman** [comment]
Shouldn't `echo mono > /sys/kernel/tracing/trace_clock` fix this?

**Comment by cnlohr** [comment]
After many hours of experimentation, it does not.  It's not clear why.  But no matter what clock is used, it still does not line up. `clock_gettime` for MONOTONIC, or MONOTNIC_RAW does not line up to events regardless of clock selected in `/sys/kernel/tracing/trace_clock` having dtime= provides a very easy work-around.

**Comment by cnlohr** [comment]
I just opened a PR #54 but will need to be reviewed, since I am so new to this code base.

**Comment by mikesart** [comment]
Pulled your PR, so hopefully this should be fixed. Thanks!
