### ISSUE TITLE
Not getting vblank events for NVIDIA (Is this expected?)

### ISSUE THREAD

**Issue by kwand** [mikesart/gpuvis#61]
As titled. 

**_What I've tried so far is:_**
- The first time I tried this was without the DRM kernel mode setting for NVIDIA enabled, so I figured turning it on might fix this (with `options nvidia_drm modeset=1` in `/etc/modprobe.d/nvidia-drm.conf`. lsmod seems to confirm that all the relevant modules* are loaded, except for `nvidia_uvm` - and `ttm` that MHWD blacklists for some reason. I haven't tried turning them on yet, as I don't quite see why they would affect this). Unfortunately, I'm still getting nothing back for drm:drm_vblank_event and running `trace-cmd report trace.dat | grep drm` confirms that it's not tracing those events

\* Specifically, I mean `drm`, `drm_kms_helper`, `nvidia`, `nvidia_drm`, and `nvidia_modeset` as reported by `lsmod | grep nvidia`.
- Searched around the issues here, and thought my case might be similar to #48 - as in `trace-cmd` being the problem, so I went and compiled it myself. Unfortunately, nothing seems to have changed.
- I'll note that `trace-cmd list | grep drm` seems to show that the `drm_vblank_event`, `drm_vblank_queued` and `drm_vblank_event_delivered` are traceable.

Does tracing DRM events simply not work for NVIDIA? (had a hard time finding anything relevant via Google) It seems quite odd if this is the case, since it appears that this should be coming from the kernel. Or are there other things that I should be turning on (DRM-related) for this to work?

_(By-the-way, I'm using Manjaro - which may/may not have anything to do with this. MHWD did botch upgrading NVIDIA drivers several times in the past, which I seem to have 'fixed' - as in I can use everything fine, to my eyes - by manually installing/uninstalling using a mix of pacman and mhwd on the virtual terminal. As to kernel/drivers/hardware, I'm on kernel 4.19, NVIDIA 460.39 drivers with an RTX 2080)_

**Comment by kwand** [comment]
After some further investigation, I discovered this line from running `dmesg | grep drm`: 
```
[    3.956752] [drm] No driver support for vblank timestamp query.
```
So, I assume this is a known NVIDIA driver issue?

**Comment by mikesart** [comment]
Yeah, nvidia doesn't use any of the mesa code and I'm not sure what tracepoints (if any) they add. There was some code written to read nvidia captures into gpuvis, but it doesn't look like it's been updated in a while and I'm not sure what the status of it is. That code is here though:

https://github.com/adamnv/gpuvis/commits/fecs3

**Comment by kwand** [comment]
OK, I'll take a look into that repo and see if I can salvage anything from there. Thanks for your help and the link!

(It's a shame that NVIDIA does so many things differently on Linux)

**Comment by mikesart** [comment]
Totally agree... Good luck!
