### ISSUE TITLE
Get rid of trace-cmd

### ISSUE THREAD

**Issue by rokups** [mikesart/gpuvis#7]
`trace-cmd` is licensed under GPL while all other dependencies use permissive licenses. This single dependency prevents incorporating this project into other projects which are under permissive license. To make this project more accessible i think `trace-cmd` should be removed and replaced with something which is under permissive license.

**Comment by mikesart** [comment]
From what I can tell, trace-cmd is destined to be replaced at some point by perf, however right now we need some trace-cmd features which perf doesn't do yet. The trace-cmd event parse file is 150k and there is no other alternative. So while I'd love to use something with a more permissive license, it just doesn't make sense for me to spend time rewriting all that when it theoretically is going away at some point in the future anyways. Thanks rokups.
