### ISSUE TITLE
QUESTION: Work with Nouveau nvidia drivers

### ISSUE THREAD

**Issue by opensusefan** [mikesart/gpuvis#84]
I just want to know does this will able to provide the stats of my nvidia gpu running iwth nouveau drivers the kde system monitor doesn't able to provide me that.

**Comment by mikesart** [comment]
The driver writer folks have to add code for gpuvis to work with it. I don’t believe anyone from nouveau has done this so you’re not going to get any information from that driver in gpuvis. Sorry.
